import type { ArtifactResponse } from "@/models/intelligence/artifacts";

export const artifactResponses: Record<string, ArtifactResponse[]> = {
  "RFQ-2026-0142": [
    {
      id: "artifact-142-briefing",
      rfqId: "RFQ-2026-0142",
      kind: "briefing",
      title: "Bid Briefing",
      version: "v1.4",
      status: "complete",
      updatedAt: "2026-03-30T10:40:00Z",
      summary:
        "Executive-ready briefing with margin posture, supplier risk, and committee notes.",
      owner: "Intelligence Engine",
    },
    {
      id: "artifact-142-profile",
      rfqId: "RFQ-2026-0142",
      kind: "workbook_profile",
      title: "Workbook Profile",
      version: "v3.0",
      status: "complete",
      updatedAt: "2026-03-29T17:10:00Z",
      summary:
        "Workbook structure and sheet coverage are synchronized with package scope.",
      owner: "Intelligence Engine",
    },
    {
      id: "artifact-142-review",
      rfqId: "RFQ-2026-0142",
      kind: "workbook_review",
      title: "Workbook Review",
      version: "v3.0",
      status: "complete",
      updatedAt: "2026-03-29T17:18:00Z",
      summary: "Workbook review shows high readiness with one low-severity note.",
      owner: "Intelligence Engine",
    },
    {
      id: "artifact-142-snapshot",
      rfqId: "RFQ-2026-0142",
      kind: "snapshot",
      title: "Intelligence Snapshot",
      version: "v1.9",
      status: "complete",
      updatedAt: "2026-03-30T10:42:00Z",
      summary:
        "Consolidated readiness snapshot combining intake, briefing, and workbook signals.",
      owner: "Intelligence Engine",
    },
  ],
  "RFQ-2026-0138": [
    {
      id: "artifact-138-briefing",
      rfqId: "RFQ-2026-0138",
      kind: "briefing",
      title: "Bid Briefing",
      version: "v0.8",
      status: "partial",
      updatedAt: "2026-03-29T12:10:00Z",
      summary: "Early briefing draft based on package understanding only.",
      owner: "Intelligence Engine",
    },
    {
      id: "artifact-138-profile",
      rfqId: "RFQ-2026-0138",
      kind: "workbook_profile",
      title: "Workbook Profile",
      version: "n/a",
      status: "not_uploaded",
      summary:
        "Waiting for the first workbook upload to generate sheet coverage.",
      owner: "Intelligence Engine",
    },
    {
      id: "artifact-138-review",
      rfqId: "RFQ-2026-0138",
      kind: "workbook_review",
      title: "Workbook Review",
      version: "n/a",
      status: "not_uploaded",
      summary: "Workbook review is unavailable until workbook intake starts.",
      owner: "Intelligence Engine",
    },
    {
      id: "artifact-138-snapshot",
      rfqId: "RFQ-2026-0138",
      kind: "snapshot",
      title: "Intelligence Snapshot",
      version: "v0.9",
      status: "partial",
      updatedAt: "2026-03-29T12:14:00Z",
      summary:
        "Partial snapshot showing complete intake and missing workbook path.",
      owner: "Intelligence Engine",
    },
  ],
  "RFQ-2026-0126": [
    {
      id: "artifact-126-briefing",
      rfqId: "RFQ-2026-0126",
      kind: "briefing",
      title: "Bid Briefing",
      version: "v1.1",
      status: "complete",
      updatedAt: "2026-03-30T08:10:00Z",
      summary:
        "Complete briefing available, but its recommendation is gated by workbook repair.",
      owner: "Intelligence Engine",
    },
    {
      id: "artifact-126-profile",
      rfqId: "RFQ-2026-0126",
      kind: "workbook_profile",
      title: "Workbook Profile",
      version: "v2.0",
      status: "failed",
      updatedAt: "2026-03-30T18:05:00Z",
      summary: "Workbook profile detected structural issues during validation.",
      owner: "Intelligence Engine",
    },
    {
      id: "artifact-126-review",
      rfqId: "RFQ-2026-0126",
      kind: "workbook_review",
      title: "Workbook Review",
      version: "v2.0",
      status: "failed",
      updatedAt: "2026-03-30T18:12:00Z",
      summary:
        "Workbook review failed with blocking section-total inconsistencies.",
      owner: "Intelligence Engine",
    },
    {
      id: "artifact-126-snapshot",
      rfqId: "RFQ-2026-0126",
      kind: "snapshot",
      title: "Intelligence Snapshot",
      version: "v1.3",
      status: "failed",
      updatedAt: "2026-03-31T07:42:00Z",
      summary:
        "Snapshot is marked failed until workbook review is repaired and rerun.",
      owner: "Intelligence Engine",
    },
  ],
  "RFQ-2026-0119": [
    {
      id: "artifact-119-briefing",
      rfqId: "RFQ-2026-0119",
      kind: "briefing",
      title: "Bid Briefing",
      version: "v1.7",
      status: "complete",
      updatedAt: "2026-03-12T09:15:00Z",
      summary: "Awarded briefing preserved for lessons learned and reuse.",
      owner: "Intelligence Engine",
    },
    {
      id: "artifact-119-profile",
      rfqId: "RFQ-2026-0119",
      kind: "workbook_profile",
      title: "Workbook Profile",
      version: "v4.0",
      status: "complete",
      updatedAt: "2026-03-11T17:20:00Z",
      summary: "Workbook profile is complete and archived.",
      owner: "Intelligence Engine",
    },
    {
      id: "artifact-119-review",
      rfqId: "RFQ-2026-0119",
      kind: "workbook_review",
      title: "Workbook Review",
      version: "v4.0",
      status: "complete",
      updatedAt: "2026-03-11T17:30:00Z",
      summary: "Workbook review closed without exceptions at award.",
      owner: "Intelligence Engine",
    },
    {
      id: "artifact-119-snapshot",
      rfqId: "RFQ-2026-0119",
      kind: "snapshot",
      title: "Intelligence Snapshot",
      version: "v2.0",
      status: "complete",
      updatedAt: "2026-03-12T09:20:00Z",
      summary: "Reference snapshot retained for benchmark comparison.",
      owner: "Intelligence Engine",
    },
  ],
  "RFQ-2026-0151": [
    {
      id: "artifact-151-briefing",
      rfqId: "RFQ-2026-0151",
      kind: "briefing",
      title: "Bid Briefing",
      version: "v0.9",
      status: "partial",
      updatedAt: "2026-03-30T14:00:00Z",
      summary:
        "Briefing is present but still guarded by scope ambiguity.",
      owner: "Intelligence Engine",
    },
    {
      id: "artifact-151-profile",
      rfqId: "RFQ-2026-0151",
      kind: "workbook_profile",
      title: "Workbook Profile",
      version: "v1.2",
      status: "partial",
      updatedAt: "2026-03-30T10:18:00Z",
      summary:
        "Workbook profile is available, with one missing calibration section.",
      owner: "Intelligence Engine",
    },
    {
      id: "artifact-151-review",
      rfqId: "RFQ-2026-0151",
      kind: "workbook_review",
      title: "Workbook Review",
      version: "v1.2",
      status: "partial",
      updatedAt: "2026-03-30T10:30:00Z",
      summary:
        "Workbook review is still open while scope clarification is pending.",
      owner: "Intelligence Engine",
    },
    {
      id: "artifact-151-snapshot",
      rfqId: "RFQ-2026-0151",
      kind: "snapshot",
      title: "Intelligence Snapshot",
      version: "v1.0",
      status: "partial",
      updatedAt: "2026-03-30T14:05:00Z",
      summary:
        "Partial snapshot indicates active progress with one remaining blocker.",
      owner: "Intelligence Engine",
    },
  ],
};
